### ISSUE TITLE
When cobrowsing, the visitor minimizes the browser or opens a new tab, the gray mask does not appear and the Cobrowsing Window still shows the last page with glance code

### ISSUE THREAD

**Issue by Comm100** [Comm100/Cobrowse#23]
![attachfilehandler5](https://user-images.githubusercontent.com/32153205/38985121-0fe42c66-43fb-11e8-931e-216577ddfaa5.png)

**Comment by jonmeadglance** [comment]
This is not a bug, but rather how the application functions.  If the customer navigates away from the domain in the same browser tab, then the agent's view will grey out.  Because the cookie that we have in the browser can see that the page was actively navigated away from, we can grey the agent view out.  When the customer minimizes the browser or opens another tab, we have no way of knowing that the customer has left the focus of the page.  We do, however, flash the agent's view when the customer comes back.
